# Generated by Django 4.2.15 on 2024-09-21 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuslanFansApp', '0003_alter_subscriptions_end_date_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 10, 22, 0, 1, 5, 262154), null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=962, max_digits=10),
        ),
    ]
