# Generated by Django 4.2.15 on 2024-09-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuslanFansApp', '0005_alter_subscriptions_end_date_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=10),
        ),
    ]
