# Generated by Django 4.2.15 on 2024-09-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RuslanFansApp', '0010_alter_notifications_sender_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='person',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=575, max_digits=10),
        ),
    ]
